services:
  docs:
    image: disease_surveillance_dashboard_local_docs
    container_name: disease_surveillance_dashboard_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./disease_surveillance_dashboard:/app/disease_surveillance_dashboard:z
    ports:
      - '9000:9000'
    command: /start-docs
